// import React from 'react';
// import { ShieldCheck, Lock, DatabaseZap, Scale, Sparkles, FileText, CheckCircle2 } from 'lucide-react';

// const SECTIONS = [
//   {
//     icon: Sparkles,
//     badge: 'Section 01',
//     title: 'Automated Resume Parsing & AI Evaluation',
//     content:
//       'RankResume AI uses Google Gemini semantic model architectures solely to extract structured candidate profile data and evaluate match density against active recruiter requisitions. Resumes submitted are never used to train public foundation models or shared with external data brokers.'
//   },
//   {
//     icon: Scale,
//     badge: 'Section 02',
//     title: 'Recruiter Integrity & Fair AI Scoring Standards',
//     content:
//       'Match scores, heuristic breakdowns, and qualification percentages generated by the platform are algorithmic decision-support metrics. Recruiters and hiring authorities retain sole responsibility for final hiring actions, ensuring compliance with global fair hiring and non-discrimination mandates.'
//   },
//   {
//     icon: DatabaseZap,
//     badge: 'Section 03',
//     title: 'Candidate Data Verification & Authentic Representation',
//     content:
//       'Job applicants represent that all submitted employment histories, education certificates, and technical portfolios are genuine and accurate. RankResume AI reserves the right to flag fraudulent credentials or automated submission spam.'
//   },
//   {
//     icon: Lock,
//     badge: 'Section 04',
//     title: 'Permanent Data Purging & Account Cascade Erasure',
//     content:
//       'Users maintain complete sovereignty over their data. Executing an account termination permanently deletes all associated resume blobs, vectorized embeddings, match evaluations, and personal authentication records within 24 hours.'
//   }
// ];

// export const TermsConditions = () => {
//   return (
//     <div className="mx-auto max-w-5xl space-y-8 px-4 py-8 font-sans">
      
//       {/* ========================================================================= */}
//       {/* --- SaaS Hero Header Banner --- */}
//       {/* ========================================================================= */}
//       <div className="relative overflow-hidden rounded-3xl border border-slate-800/80 bg-slate-900/70 p-6 sm:p-8 backdrop-blur-xl shadow-2xl">
//         {/* Hardware-Accelerated Ambient Glows */}
//         <div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-blue-600/15 blur-3xl transform-gpu will-change-transform" />
//         <div className="pointer-events-none absolute -left-20 -bottom-20 h-64 w-64 rounded-full bg-pink-600/15 blur-3xl transform-gpu will-change-transform" />
//         <div className="pointer-events-none absolute left-0 top-0 h-[1px] w-full bg-gradient-to-r from-transparent via-cyan-500/40 to-transparent" />

//         <div className="relative z-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-center">
//           <div className="space-y-2">
//             <div className="inline-flex items-center gap-1.5 rounded-full border border-cyan-500/30 bg-cyan-950/40 px-3 py-0.5 text-xs font-semibold text-cyan-300">
//               <ShieldCheck className="h-3.5 w-3.5 text-cyan-400" />
//               <span>Governance & Algorithmic Ethics</span>
//             </div>
            
//             <h1 className="text-2xl sm:text-3xl md:text-4xl font-black tracking-tight text-white">
//               Terms of Service & <span className="bg-gradient-to-r from-cyan-400 via-indigo-300 to-pink-400 bg-clip-text text-transparent">AI Ethics</span>
//             </h1>
            
//             <p className="text-xs sm:text-sm text-slate-400 max-w-xl leading-relaxed">
//               Last revised: August 2026. Standard operating protocols governing parsing pipelines, applicant sovereignty, and algorithmic match scoring.
//             </p>
//           </div>

//           <div className="flex items-center gap-3 shrink-0">
//             <div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-cyan-500/30 bg-cyan-950/40 text-cyan-400 shadow-xl shadow-cyan-500/10">
//               <FileText className="h-6 w-6" />
//             </div>
//           </div>
//         </div>
//       </div>

//       {/* ========================================================================= */}
//       {/* --- Structured Terms Grid --- */}
//       {/* ========================================================================= */}
//       <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
//         {SECTIONS.map((item, idx) => {
//           const Icon = item.icon;
//           return (
//             <div
//               key={idx}
//               className="group relative overflow-hidden rounded-3xl border border-slate-800/80 bg-slate-900/60 p-6 sm:p-7 backdrop-blur-xl transition-all duration-200 hover:border-cyan-500/40 hover:bg-slate-900/90 shadow-xl"
//             >
//               {/* Top Card Horizon Accent */}
//               <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-slate-700/50 to-transparent group-hover:via-cyan-500/40 transition-all duration-300" />

//               <div className="flex items-center justify-between">
//                 <div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-cyan-500/30 bg-cyan-950/40 text-cyan-400 shadow-inner">
//                   <Icon className="h-5 w-5" />
//                 </div>
//                 <span className="font-mono text-[10px] font-bold uppercase tracking-widest text-slate-500">
//                   {item.badge}
//                 </span>
//               </div>

//               <h2 className="mt-4 text-sm font-bold text-white group-hover:text-cyan-300 transition-colors">
//                 {item.title}
//               </h2>
              
//               <p className="mt-2.5 text-xs leading-relaxed text-slate-400">
//                 {item.content}
//               </p>
//             </div>
//           );
//         })}
//       </div>

//       {/* ========================================================================= */}
//       {/* --- Compliance & Privacy Footer Bar --- */}
//       {/* ========================================================================= */}
//       <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-2xl border border-slate-800 bg-slate-950/70 p-4 text-xs text-slate-400 backdrop-blur-md shadow-inner">
//         <div className="flex items-center gap-2">
//           <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0" />
//           <span>Questions regarding our privacy frameworks? Contact <a href="mailto:privacy@rankresume.ai" className="font-semibold text-cyan-400 hover:text-cyan-300 underline underline-offset-2">privacy@rankresume.ai</a></span>
//         </div>
//         <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-slate-300 border border-slate-800 bg-slate-900 px-3 py-1 rounded-xl self-start sm:self-auto">
//           SOC-2 & GDPR Compliant
//         </span>
//       </div>

//     </div>
//   );
// };

// export default TermsConditions;







import React from 'react';
import { ShieldCheck, Lock, DatabaseZap, Scale, Sparkles, FileText, CheckCircle2 } from 'lucide-react';

const SECTIONS = [
  {
    icon: Sparkles,
    badge: 'Section 01',
    title: 'Automated Resume Parsing & AI Evaluation',
    content:
      'RankResume AI uses Google Gemini semantic model architectures solely to extract structured candidate profile data and evaluate match density against active recruiter requisitions. Resumes submitted are never used to train public foundation models or shared with external data brokers.'
  },
  {
    icon: Scale,
    badge: 'Section 02',
    title: 'Recruiter Integrity & Fair AI Scoring Standards',
    content:
      'Match scores, heuristic breakdowns, and qualification percentages generated by the platform are algorithmic decision-support metrics. Recruiters and hiring authorities retain sole responsibility for final hiring actions, ensuring compliance with global fair hiring and non-discrimination mandates.'
  },
  {
    icon: DatabaseZap,
    badge: 'Section 03',
    title: 'Candidate Data Verification & Authentic Representation',
    content:
      'Job applicants represent that all submitted employment histories, education certificates, and technical portfolios are genuine and accurate. RankResume AI reserves the right to flag fraudulent credentials or automated submission spam.'
  },
  {
    icon: Lock,
    badge: 'Section 04',
    title: 'Permanent Data Purging & Account Cascade Erasure',
    content:
      'Users maintain complete sovereignty over their data. Executing an account termination permanently deletes all associated resume blobs, vectorized embeddings, match evaluations, and personal authentication records within 24 hours.'
  }
];

export const TermsConditions = () => {
  return (
    <div className="mx-auto max-w-5xl space-y-8 px-4 py-8 font-sans text-slate-900 antialiased">
      
      {/* Background Soft Ambient Orbs */}
      <div className="pointer-events-none fixed inset-0 z-0 overflow-hidden transform-gpu">
        <div className="absolute -top-32 -left-20 h-[500px] w-[500px] rounded-full bg-blue-500/20 blur-[120px] will-change-transform" />
        <div className="absolute top-1/3 -right-20 h-[520px] w-[520px] rounded-full bg-pink-500/20 blur-[130px] will-change-transform" />
      </div>

      {/* ========================================================================= */}
      {/* --- SaaS Hero Header Banner --- */}
      {/* ========================================================================= */}
      <div className="relative overflow-hidden rounded-3xl border border-white/90 bg-white/80 p-6 sm:p-8 backdrop-blur-xl shadow-[0_20px_50px_rgba(37,99,235,0.12),0_10px_30px_rgba(236,72,153,0.1)] transition-all">
        {/* Hardware-Accelerated Ambient Glows */}
        <div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-gradient-to-br from-pink-500/30 via-rose-400/20 to-transparent blur-3xl transform-gpu will-change-transform" />
        <div className="pointer-events-none absolute -left-20 -bottom-20 h-64 w-64 rounded-full bg-gradient-to-tr from-blue-500/30 via-sky-400/20 to-transparent blur-3xl transform-gpu will-change-transform" />
        <div className="pointer-events-none absolute left-0 top-0 h-[3px] w-full bg-gradient-to-r from-blue-600 via-pink-500 to-indigo-600 shadow-[0_0_12px_rgba(236,72,153,0.4)]" />

        <div className="relative z-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-center">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-1.5 rounded-full border border-blue-200 bg-blue-50/80 px-3.5 py-1 text-xs font-bold text-blue-700 shadow-xs backdrop-blur-sm">
              <ShieldCheck className="h-4 w-4 text-blue-600 stroke-[2.5]" />
              <span>Governance & Algorithmic Ethics</span>
            </div>
            
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-black tracking-tight text-slate-950">
              Terms of Service & <span className="bg-gradient-to-r from-blue-600 via-indigo-600 to-pink-600 bg-clip-text text-transparent">AI Ethics</span>
            </h1>
            
            <p className="text-xs sm:text-sm font-semibold text-slate-600 max-w-xl leading-relaxed">
              Standard operating protocols governing parsing pipelines, applicant sovereignty, and algorithmic match scoring.
            </p>
          </div>

          <div className="flex items-center gap-3 shrink-0">
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-blue-200 bg-blue-50 text-blue-700 shadow-md shadow-blue-500/10">
              <FileText className="h-7 w-7 stroke-[2.2]" />
            </div>
          </div>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* --- Structured Terms Grid --- */}
      {/* ========================================================================= */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {SECTIONS.map((item, idx) => {
          const Icon = item.icon;
          return (
            <div
              key={idx}
              className="group relative overflow-hidden rounded-3xl border border-white/90 bg-white/85 p-6 sm:p-7 backdrop-blur-xl transition-all duration-200 hover:border-blue-300 hover:bg-white hover:shadow-[0_15px_40px_rgba(37,99,235,0.1)] shadow-xs"
            >
              {/* Top Card Horizon Accent */}
              <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-blue-500/20 to-transparent group-hover:via-pink-500/40 transition-all duration-300" />

              <div className="flex items-center justify-between">
                <div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-blue-200 bg-blue-50 text-blue-600 shadow-xs">
                  <Icon className="h-5 w-5 stroke-[2.2]" />
                </div>
                <span className="font-mono text-[11px] font-extrabold uppercase tracking-widest text-slate-500">
                  {item.badge}
                </span>
              </div>

              <h2 className="mt-4 text-sm font-black text-slate-950 group-hover:text-blue-700 transition-colors">
                {item.title}
              </h2>
              
              <p className="mt-2.5 text-xs font-semibold leading-relaxed text-slate-600">
                {item.content}
              </p>
            </div>
          );
        })}
      </div>

      {/* ========================================================================= */}
      {/* --- Compliance & Privacy Footer Bar --- */}
      {/* ========================================================================= */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white/90 p-4 text-xs font-semibold text-slate-700 backdrop-blur-md shadow-xs">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="h-4 w-4 text-emerald-600 stroke-[2.5] shrink-0" />
          <span>
            Questions regarding our privacy frameworks? Contact{' '}
            <a href="mailto:privacy@rankresume.ai" className="font-extrabold text-blue-700 hover:text-pink-600 underline underline-offset-2 transition-colors">
              privacy@rankresume.ai
            </a>
          </span>
        </div>
        <span className="font-mono text-[10px] font-extrabold uppercase tracking-wider text-blue-700 border border-blue-200 bg-blue-50 px-3 py-1 rounded-xl self-start sm:self-auto shadow-2xs">
          SOC-2 & GDPR Compliant
        </span>
      </div>

    </div>
  );
};

export default TermsConditions;