import React from 'react';
import { ShieldCheck, FileCheck, Lock, DatabaseZap, Scale, Sparkles } from 'lucide-react';

const SECTIONS = [
  {
    icon: Sparkles,
    badge: 'Section 01',
    title: 'Automated Resume Parsing & AI Evaluation',
    content:
      'RankResume AI uses Google Gemini semantic model architectures solely to extract structured candidate profile data and evaluate match density against active recruiter requisitions. Resumes submitted are never used to train public foundation models or shared with external data brokers.'
  },
  {
    icon: Scale,
    badge: 'Section 02',
    title: 'Recruiter Integrity & Fair AI Scoring Standards',
    content:
      'Match scores, heuristic breakdowns, and qualification percentages generated by the platform are algorithmic decision-support metrics. Recruiters and hiring authorities retain sole responsibility for final hiring actions, ensuring compliance with global fair hiring and non-discrimination mandates.'
  },
  {
    icon: DatabaseZap,
    badge: 'Section 03',
    title: 'Candidate Data Verification & Authentic Representation',
    content:
      'Job applicants represent that all submitted employment histories, education certificates, and technical portfolios are genuine and accurate. RankResume AI reserves the right to flag fraudulent credentials or automated submission spam.'
  },
  {
    icon: Lock,
    badge: 'Section 04',
    title: 'Permanent Data Purging & Account Cascade Erasure',
    content:
      'Users maintain complete sovereignty over their data. Executing an account termination permanently deletes all associated Supabase resume blobs, vectorized embeddings, match evaluations, and personal authentication records within 24 hours.'
  }
];

export const TermsConditions = () => {
  return (
    <div className="mx-auto max-w-5xl space-y-10 px-4 py-8">
      {/* Header Banner */}
      <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-b from-zinc-900/90 via-zinc-900/60 to-black/80 p-8 backdrop-blur-2xl shadow-2xl">
        <div className="absolute -right-12 -top-12 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl pointer-events-none" />
        
        <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-wider text-indigo-300">
          <ShieldCheck className="h-3 w-3" />
          Governance & Compliance
        </div>
        <h1 className="mt-3 text-2xl font-black tracking-tight text-white sm:text-3xl">
          Terms of Service & AI Ethics Policy
        </h1>
        <p className="mt-1 text-sm text-zinc-400">
          Last revised: August 2026. Standard protocol governing parsing pipelines, applicant privacy, and algorithmic scoring.
        </p>
      </div>

      {/* Structured Terms Grid */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {SECTIONS.map((item, idx) => {
          const Icon = item.icon;
          return (
            <div
              key={idx}
              className="relative overflow-hidden rounded-3xl border border-zinc-800/80 bg-zinc-900/40 p-6 backdrop-blur-xl transition-all duration-300 hover:border-zinc-700/80 hover:bg-zinc-900/60 hover:shadow-xl hover:shadow-black/40"
            >
              <div className="flex items-center justify-between">
                <div className="flex h-9 w-9 items-center justify-center rounded-xl border border-indigo-500/20 bg-indigo-500/10 text-indigo-400">
                  <Icon className="h-4 w-4" />
                </div>
                <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-500">
                  {item.badge}
                </span>
              </div>
              <h2 className="mt-4 text-sm font-bold text-zinc-100">
                {item.title}
              </h2>
              <p className="mt-2 text-xs leading-relaxed text-zinc-400">
                {item.content}
              </p>
            </div>
          );
        })}
      </div>

      {/* Compliance Footer Note */}
      <div className="flex items-center justify-between rounded-2xl border border-zinc-800 bg-zinc-950/60 p-4 text-[11px] text-zinc-400 backdrop-blur-md">
        <span>Questions regarding our privacy frameworks? Contact <span className="text-indigo-400 font-medium">privacy@rankresume.ai</span></span>
        <span className="font-semibold text-zinc-300">SOC-2 & GDPR Compatible</span>
      </div>
    </div>
  );
};

export default TermsConditions;